# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

#
# Knative-Kafka Dependency Specification
#
# Note - Most of the following were lifted from the Knative Eventing Gopkg.toml
#        file so that our implementation is in sync with theirs.  This is
#        important since our implementation makes calls into the Knative Eventing
#        source.
#

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[prune.project]]
  name = "k8s.io/code-generator"
  unused-packages = false
  non-go = false

[[prune.project]]
  name = "knative.dev/test-infra"
  non-go = false

[[prune.project]]
  name = "knative.dev/pkg"
  unused-packages = false
  non-go = false

# # Align With Knative Eventing 0.10.2
[[override]]
  name = "knative.dev/pkg"
  branch = "master"

[[override]]
  name = "gopkg.in/yaml.v2"
  version = "v2.2.4"

# Align With Knative Eventing 0.10.2 (GKE Compatability)
[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.16.4"

# Align With Knative Eventing 0.10.2 (GKE Compatability)
[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.16.4"

# Overridden to ensure compatibility with GKE
# GKE version as of 2019-01-24 is 1.11
# controller-runtime 0.1.9 requires at least 1.12
[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.16.4"

# Align With Knative Eventing 0.10.2 (GKE Compatability)
[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.16.4"

# Align With Knative Eventing 0.10.2 (GKE Compatability)
[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.16.4"

# Align With Knative Eventing 0.10.2 (Can be removed once Knative is on K8S 1.13 which has fix https://github.com/kubernetes/kubernetes/pull/71296)
[[override]]
  name = "github.com/json-iterator/go"
  revision = "f2b4162afba35581b6d4a50d3b8f34e33c144682"

# Align With Knative Eventing 0.10.2
[[constraint]]
  name = "knative.dev/eventing"
  branch = "master"

# Knative-Kafka Dependency Only!
[[constraint]]
  name = "github.com/confluentinc/confluent-kafka-go"
  version = "~v1.0.0"

# Align With Knative Eventing 0.10.2
[[override]]
  name = "github.com/cloudevents/sdk-go"
  version = "=0.10.0"

# Align With Knative Eventing 0.10.2
# needed because pkg upgraded
[[override]]
  name = "go.uber.org/zap"
  revision = "67bc79d13d155c02fd008f721863ff8cc5f30659"

# For dependency below: Refer to issue https://github.com/golang/dep/issues/1799
[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"
  version="v1.4.7"

[[constraint]]
   name = "github.com/kyma-incubator/knative-kafka"
   branch = "master"

# Align With Knative Eventing 0.10.2 (Manually extracted from knative-eventing Gopkg.lock)
[[override]]
  name = "contrib.go.opencensus.io/exporter/stackdriver"
  revision = "68e3d742b03c099c35428443886e65d9587c8d76"
